//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountHolder.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountHolder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проблема с интернет соединением!.
        /// </summary>
        public static string AccountErrorMessage1 {
            get {
                return ResourceManager.GetString("AccountErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка со входом! Проверьте сервер и данные аккаунта..
        /// </summary>
        public static string AccountErrorMessage2 {
            get {
                return ResourceManager.GetString("AccountErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string AccountErrorTitle {
            get {
                return ResourceManager.GetString("AccountErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт:.
        /// </summary>
        public static string AccountText {
            get {
                return ResourceManager.GetString("AccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить аккаунт.
        /// </summary>
        public static string AddAccountText {
            get {
                return ResourceManager.GetString("AddAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить список.
        /// </summary>
        public static string AddListBtn {
            get {
                return ResourceManager.GetString("AddListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество аккаунтов:.
        /// </summary>
        public static string AmountAccsText {
            get {
                return ResourceManager.GetString("AmountAccsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новый список.
        /// </summary>
        public static string CreateNewListBtn {
            get {
                return ResourceManager.GetString("CreateNewListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить аккаунт.
        /// </summary>
        public static string DeleteAccBtn {
            get {
                return ResourceManager.GetString("DeleteAccBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить список.
        /// </summary>
        public static string DeleteListBtn {
            get {
                return ResourceManager.GetString("DeleteListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла:.
        /// </summary>
        public static string FileNameText {
            get {
                return ResourceManager.GetString("FileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID Золотого яблока.
        /// </summary>
        public static string GoldenAppleText {
            get {
                return ResourceManager.GetString("GoldenAppleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для смены языка необходимо перезапустить программу..
        /// </summary>
        public static string LanguageMessage {
            get {
                return ResourceManager.GetString("LanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить список.
        /// </summary>
        public static string LoadListBtn {
            get {
                return ResourceManager.GetString("LoadListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список аккаунтов не создан!.
        /// </summary>
        public static string MainAddAccErrorMessage {
            get {
                return ResourceManager.GetString("MainAddAccErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список аккаунтов не создан!.
        /// </summary>
        public static string MainAddListErrorMessage {
            get {
                return ResourceManager.GetString("MainAddListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при удалении файла!.
        /// </summary>
        public static string MainDeleteFileErrorMessage {
            get {
                return ResourceManager.GetString("MainDeleteFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла какая-то ошибка! Обратитесь к администрации!.
        /// </summary>
        public static string MainErrorMessage1 {
            get {
                return ResourceManager.GetString("MainErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружена попытка несанкционированого доступа!.
        /// </summary>
        public static string MainErrorMessage2 {
            get {
                return ResourceManager.GetString("MainErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша подписка не активна или не соотвествует уровень!.
        /// </summary>
        public static string MainErrorMessage3 {
            get {
                return ResourceManager.GetString("MainErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка!.
        /// </summary>
        public static string MainGoAccErrorMessage {
            get {
                return ResourceManager.GetString("MainGoAccErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список аккаунтов не создан или количество аккаунтов 0!.
        /// </summary>
        public static string MainGoAccErrorMessage2 {
            get {
                return ResourceManager.GetString("MainGoAccErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово!.
        /// </summary>
        public static string MainGoAccSuccessMessage {
            get {
                return ResourceManager.GetString("MainGoAccSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при загрузке файла!.
        /// </summary>
        public static string MainLoadListErrorMessage {
            get {
                return ResourceManager.GetString("MainLoadListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список аккаунтов не создан или количество аккаунтов 0!.
        /// </summary>
        public static string MainTutorailErrorMessage2 {
            get {
                return ResourceManager.GetString("MainTutorailErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка!.
        /// </summary>
        public static string MainTutorialErrorMessage {
            get {
                return ResourceManager.GetString("MainTutorialErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово!.
        /// </summary>
        public static string MainTutorialSuccessMessage {
            get {
                return ResourceManager.GetString("MainTutorialSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно обновление.
        /// </summary>
        public static string MainUpdateMessage1 {
            get {
                return ResourceManager.GetString("MainUpdateMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустите лаунчер чтобы обновиться..
        /// </summary>
        public static string MainUpdateMessage2 {
            get {
                return ResourceManager.GetString("MainUpdateMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Арабский.
        /// </summary>
        public static string ServerArabic {
            get {
                return ResourceManager.GetString("ServerArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Австралия.
        /// </summary>
        public static string ServerAustralia {
            get {
                return ResourceManager.GetString("ServerAustralia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Болгария.
        /// </summary>
        public static string ServerBulgaria {
            get {
                return ResourceManager.GetString("ServerBulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канада.
        /// </summary>
        public static string ServerCanada {
            get {
                return ResourceManager.GetString("ServerCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Англия.
        /// </summary>
        public static string ServerEngland {
            get {
                return ResourceManager.GetString("ServerEngland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Франция Gaia.
        /// </summary>
        public static string ServerFranceGaia {
            get {
                return ResourceManager.GetString("ServerFranceGaia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Франция Ouranos.
        /// </summary>
        public static string ServerFranceOuranos {
            get {
                return ResourceManager.GetString("ServerFranceOuranos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Германия.
        /// </summary>
        public static string ServerGermany {
            get {
                return ResourceManager.GetString("ServerGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интернациональный.
        /// </summary>
        public static string ServerInternational {
            get {
                return ResourceManager.GetString("ServerInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Норвегия.
        /// </summary>
        public static string ServerNorway {
            get {
                return ResourceManager.GetString("ServerNorway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Польша.
        /// </summary>
        public static string ServerPoland {
            get {
                return ResourceManager.GetString("ServerPoland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Румыния.
        /// </summary>
        public static string ServerRomain {
            get {
                return ResourceManager.GetString("ServerRomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Россия.
        /// </summary>
        public static string ServerRussia {
            get {
                return ResourceManager.GetString("ServerRussia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испания.
        /// </summary>
        public static string ServerSpain {
            get {
                return ResourceManager.GetString("ServerSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Швеция.
        /// </summary>
        public static string ServerSweden {
            get {
                return ResourceManager.GetString("ServerSweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер.
        /// </summary>
        public static string ServerText {
            get {
                return ResourceManager.GetString("ServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на США.
        /// </summary>
        public static string ServerUSA {
            get {
                return ResourceManager.GetString("ServerUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этап.
        /// </summary>
        public static string StageText {
            get {
                return ResourceManager.GetString("StageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогнать список.
        /// </summary>
        public static string StartListBtn {
            get {
                return ResourceManager.GetString("StartListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пройти обучение.
        /// </summary>
        public static string StartTutorialBtn {
            get {
                return ResourceManager.GetString("StartTutorialBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус:.
        /// </summary>
        public static string StatusText2 {
            get {
                return ResourceManager.GetString("StatusText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на шаг.
        /// </summary>
        public static string StepText {
            get {
                return ResourceManager.GetString("StepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обучение.
        /// </summary>
        public static string TutorialText {
            get {
                return ResourceManager.GetString("TutorialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string TutorialYesText {
            get {
                return ResourceManager.GetString("TutorialYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стаж.
        /// </summary>
        public static string YearsText {
            get {
                return ResourceManager.GetString("YearsText", resourceCulture);
            }
        }
    }
}
