using System;
using System.Collections.Generic;

namespace QuallyFlash
{
    public class Equipment
    {
        private readonly Dictionary<string, string> ids = new Dictionary<string, string>
        {
            {"https://www.lowadi.com-BridleClassic1", "4"},
            {"https://www.lowadi.com-BridleClassic2", "196"},
            {"https://www.lowadi.com-BridleClassic3", "5"},
            {"https://www.lowadi.com-BridleWestern1", "3"},
            {"https://www.lowadi.com-BridleWestern2", "312"},
            {"https://www.lowadi.com-BridleWestern3", "2"},
            {"https://www.lowadi.com-SaddleClassic1", "12"},
            {"https://www.lowadi.com-SaddleClassic2", "198"},
            {"https://www.lowadi.com-SaddleClassic3", "14"},
            {"https://www.lowadi.com-SaddleWestern1", "15"},
            {"https://www.lowadi.com-SaddleWestern2", "311"},
            {"https://www.lowadi.com-SaddleWestern3", "16"},
            {"https://www.lowadi.com-RampClassic", "399"},
            {"https://www.lowadi.com-RampWestern", "400"},
            {"https://www.lowadi.com-Bandages", "402"},
            {"https://www.lowadi.com-Forehead", "401"},

            {"https://ca.howrse.com-BridleClassic1", "14"},
            {"https://ca.howrse.com-BridleClassic2", "145"},
            {"https://ca.howrse.com-BridleClassic3", "15"},
            {"https://ca.howrse.com-BridleWestern1", "102"},
            {"https://ca.howrse.com-BridleWestern2", "262"},
            {"https://ca.howrse.com-BridleWestern3", "103"},
            {"https://ca.howrse.com-SaddleClassic1", "11"},
            {"https://ca.howrse.com-SaddleClassic2", "147"},
            {"https://ca.howrse.com-SaddleClassic3", "13"},
            {"https://ca.howrse.com-SaddleWestern1", "99"},
            {"https://ca.howrse.com-SaddleWestern2", "261"},
            {"https://ca.howrse.com-SaddleWestern3", "100"},
            {"https://ca.howrse.com-RampClassic", "349"},
            {"https://ca.howrse.com-RampWestern", "350"},
            {"https://ca.howrse.com-Bandages", "352"},
            {"https://ca.howrse.com-Forehead", "351"},

            {"https://ouranos.equideow.com-BridleClassic1", "14"},
            {"https://ouranos.equideow.com-BridleClassic2", "137"},
            {"https://ouranos.equideow.com-BridleClassic3", "15"},
            {"https://ouranos.equideow.com-BridleWestern1", "122"},
            {"https://ouranos.equideow.com-BridleWestern2", "254"},
            {"https://ouranos.equideow.com-BridleWestern3", "121"},
            {"https://ouranos.equideow.com-SaddleClassic1", "11"},
            {"https://ouranos.equideow.com-SaddleClassic2", "139"},
            {"https://ouranos.equideow.com-SaddleClassic3", "13"},
            {"https://ouranos.equideow.com-SaddleWestern1", "125"},
            {"https://ouranos.equideow.com-SaddleWestern2", "253"},
            {"https://ouranos.equideow.com-SaddleWestern3", "126"},
            {"https://ouranos.equideow.com-RampClassic", "342"},
            {"https://ouranos.equideow.com-RampWestern", "343"},
            {"https://ouranos.equideow.com-Bandages", "345"},
            {"https://ouranos.equideow.com-Forehead", "344"},

            {"https://gaia.equideow.com-BridleClassic1", "14"},
            {"https://gaia.equideow.com-BridleClassic2", "138"},
            {"https://gaia.equideow.com-BridleClassic3", "15"},
            {"https://gaia.equideow.com-BridleWestern1", "123"},
            {"https://gaia.equideow.com-BridleWestern2", "255"},
            {"https://gaia.equideow.com-BridleWestern3", "122"},
            {"https://gaia.equideow.com-SaddleClassic1", "11"},
            {"https://gaia.equideow.com-SaddleClassic2", "140"},
            {"https://gaia.equideow.com-SaddleClassic3", "13"},
            {"https://gaia.equideow.com-SaddleWestern1", "126"},
            {"https://gaia.equideow.com-SaddleWestern2", "254"},
            {"https://gaia.equideow.com-SaddleWestern3", "127"},
            {"https://gaia.equideow.com-RampClassic", "343"},
            {"https://gaia.equideow.com-RampWestern", "344"},
            {"https://gaia.equideow.com-Bandages", "346"},
            {"https://gaia.equideow.com-Forehead", "345"},

            {"https://www.howrse.de-BridleClassic1", "14"},
            {"https://www.howrse.de-BridleClassic2", "138"},
            {"https://www.howrse.de-BridleClassic3", "15"},
            {"https://www.howrse.de-BridleWestern1", "102"},
            {"https://www.howrse.de-BridleWestern2", "255"},
            {"https://www.howrse.de-BridleWestern3", "103"},
            {"https://www.howrse.de-SaddleClassic1", "11"},
            {"https://www.howrse.de-SaddleClassic2", "140"},
            {"https://www.howrse.de-SaddleClassic3", "13"},
            {"https://www.howrse.de-SaddleWestern1", "99"},
            {"https://www.howrse.de-SaddleWestern2", "254"},
            {"https://www.howrse.de-SaddleWestern3", "100"},
            {"https://www.howrse.de-RampClassic", "342"},
            {"https://www.howrse.de-RampWestern", "343"},
            {"https://www.howrse.de-Bandages", "345"},
            {"https://www.howrse.de-Forehead", "344"},

            {"https://www.howrse.com-BridleClassic1", "14"},
            {"https://www.howrse.com-BridleClassic2", "145"},
            {"https://www.howrse.com-BridleClassic3", "15"},
            {"https://www.howrse.com-BridleWestern1", "102"},
            {"https://www.howrse.com-BridleWestern2", "262"},
            {"https://www.howrse.com-BridleWestern3", "103"},
            {"https://www.howrse.com-SaddleClassic1", "11"},
            {"https://www.howrse.com-SaddleClassic2", "147"},
            {"https://www.howrse.com-SaddleClassic3", "13"},
            {"https://www.howrse.com-SaddleWestern1", "99"},
            {"https://www.howrse.com-SaddleWestern2", "261"},
            {"https://www.howrse.com-SaddleWestern3", "100"},
            {"https://www.howrse.com-RampClassic", "349"},
            {"https://www.howrse.com-RampWestern", "350"},
            {"https://www.howrse.com-Bandages", "352"},
            {"https://www.howrse.com-Forehead", "351"},

            {"https://us.howrse.com-BridleClassic1", "14"},
            {"https://us.howrse.com-BridleClassic2", "145"},
            {"https://us.howrse.com-BridleClassic3", "15"},
            {"https://us.howrse.com-BridleWestern1", "102"},
            {"https://us.howrse.com-BridleWestern2", "262"},
            {"https://us.howrse.com-BridleWestern3", "103"},
            {"https://us.howrse.com-SaddleClassic1", "11"},
            {"https://us.howrse.com-SaddleClassic2", "147"},
            {"https://us.howrse.com-SaddleClassic3", "13"},
            {"https://us.howrse.com-SaddleWestern1", "99"},
            {"https://us.howrse.com-SaddleWestern2", "261"},
            {"https://us.howrse.com-SaddleWestern3", "100"},
            {"https://us.howrse.com-RampClassic", "349"},
            {"https://us.howrse.com-RampWestern", "350"},
            {"https://us.howrse.com-Bandages", "352"},
            {"https://us.howrse.com-Forehead", "351"},

            {"https://www.howrse.co.uk-BridleClassic1", "14"},
            {"https://www.howrse.co.uk-BridleClassic2", "145"},
            {"https://www.howrse.co.uk-BridleClassic3", "15"},
            {"https://www.howrse.co.uk-BridleWestern1", "102"},
            {"https://www.howrse.co.uk-BridleWestern2", "262"},
            {"https://www.howrse.co.uk-BridleWestern3", "103"},
            {"https://www.howrse.co.uk-SaddleClassic1", "11"},
            {"https://www.howrse.co.uk-SaddleClassic2", "147"},
            {"https://www.howrse.co.uk-SaddleClassic3", "13"},
            {"https://www.howrse.co.uk-SaddleWestern1", "99"},
            {"https://www.howrse.co.uk-SaddleWestern2", "261"},
            {"https://www.howrse.co.uk-SaddleWestern3", "100"},
            {"https://www.howrse.co.uk-RampClassic", "356"},
            {"https://www.howrse.co.uk-RampWestern", "357"},
            {"https://www.howrse.co.uk-Bandages", "359"},
            {"https://www.howrse.co.uk-Forehead", "358"},

            {"https://au.howrse.com-BridleClassic1", "14"},
            {"https://au.howrse.com-BridleClassic2", "145"},
            {"https://au.howrse.com-BridleClassic3", "15"},
            {"https://au.howrse.com-BridleWestern1", "102"},
            {"https://au.howrse.com-BridleWestern2", "262"},
            {"https://au.howrse.com-BridleWestern3", "103"},
            {"https://au.howrse.com-SaddleClassic1", "11"},
            {"https://au.howrse.com-SaddleClassic2", "147"},
            {"https://au.howrse.com-SaddleClassic3", "13"},
            {"https://au.howrse.com-SaddleWestern1", "99"},
            {"https://au.howrse.com-SaddleWestern2", "261"},
            {"https://au.howrse.com-SaddleWestern3", "100"},
            {"https://au.howrse.com-RampClassic", "349"},
            {"https://au.howrse.com-RampWestern", "350"},
            {"https://au.howrse.com-Bandages", "352"},
            {"https://au.howrse.com-Forehead", "351"},

            {"https://www.caballow.com-BridleClassic1", "14"},
            {"https://www.caballow.com-BridleClassic2", "137"},
            {"https://www.caballow.com-BridleClassic3", "15"},
            {"https://www.caballow.com-BridleWestern1", "122"},
            {"https://www.caballow.com-BridleWestern2", "253"},
            {"https://www.caballow.com-BridleWestern3", "121"},
            {"https://www.caballow.com-SaddleClassic1", "11"},
            {"https://www.caballow.com-SaddleClassic2", "139"},
            {"https://www.caballow.com-SaddleClassic3", "13"},
            {"https://www.caballow.com-SaddleWestern1", "125"},
            {"https://www.caballow.com-SaddleWestern2", "252"},
            {"https://www.caballow.com-SaddleWestern3", "126"},
            {"https://www.caballow.com-RampClassic", "340"},
            {"https://www.caballow.com-RampWestern", "341"},
            {"https://www.caballow.com-Bandages", "343"},
            {"https://www.caballow.com-Forehead", "342"},

            {"https://www.howrse.com.pt-BridleClassic1", "14"},
            {"https://www.howrse.com.pt-BridleClassic2", "145"},
            {"https://www.howrse.com.pt-BridleClassic3", "15"},
            {"https://www.howrse.com.pt-SaddleClassic1", "11"},
            {"https://www.howrse.com.pt-SaddleClassic2", "147"},
            {"https://www.howrse.com.pt-SaddleClassic3", "13"},
            {"https://www.howrse.com.pt-RampClassic", "349"},
            {"https://www.howrse.com.pt-Bandages", "352"},
            {"https://www.howrse.com.pt-Forehead", "351"},

            {"https://br.howrse.com-BridleClassic1", "14"},
            {"https://br.howrse.com-BridleClassic2", "145"},
            {"https://br.howrse.com-BridleClassic3", "15"},
            {"https://br.howrse.com-BridleWestern1", "102"},
            {"https://br.howrse.com-BridleWestern2", "262"},
            {"https://br.howrse.com-BridleWestern3", "103"},
            {"https://br.howrse.com-SaddleClassic1", "11"},
            {"https://br.howrse.com-SaddleClassic2", "147"},
            {"https://br.howrse.com-SaddleClassic3", "13"},
            {"https://br.howrse.com-SaddleWestern1", "99"},
            {"https://br.howrse.com-SaddleWestern2", "261"},
            {"https://br.howrse.com-SaddleWestern3", "100"},
            {"https://br.howrse.com-RampClassic", "349"},
            {"https://br.howrse.com-RampWestern", "350"},
            {"https://br.howrse.com-Bandages", "352"},
            {"https://br.howrse.com-Forehead", "351"},

            {"https://www.howrse.co.il-BridleClassic1", "14"},
            {"https://www.howrse.co.il-BridleClassic2", "145"},
            {"https://www.howrse.co.il-BridleClassic3", "15"},
            {"https://www.howrse.co.il-SaddleClassic1", "11"},
            {"https://www.howrse.co.il-SaddleClassic2", "147"},
            {"https://www.howrse.co.il-SaddleClassic3", "13"},
            {"https://www.howrse.co.il-RampClassic", "349"},
            {"https://www.howrse.co.il-Bandages", "352"},
            {"https://www.howrse.co.il-Forehead", "351"},

            {"https://www.howrse.it-BridleClassic1", "14"},
            {"https://www.howrse.it-BridleClassic2", "145"},
            {"https://www.howrse.it-BridleClassic3", "15"},
            {"https://www.howrse.it-BridleWestern1", "102"},
            {"https://www.howrse.it-BridleWestern2", "262"},
            {"https://www.howrse.it-BridleWestern3", "103"},
            {"https://www.howrse.it-SaddleClassic1", "11"},
            {"https://www.howrse.it-SaddleClassic2", "147"},
            {"https://www.howrse.it-SaddleClassic3", "13"},
            {"https://www.howrse.it-SaddleWestern1", "99"},
            {"https://www.howrse.it-SaddleWestern2", "261"},
            {"https://www.howrse.it-SaddleWestern3", "100"},
            {"https://www.howrse.it-RampClassic", "349"},
            {"https://www.howrse.it-RampWestern", "350"},
            {"https://www.howrse.it-Bandages", "352"},
            {"https://www.howrse.it-Forehead", "351"},

            {"https://nl.howrse.com-BridleClassic1", "14"},
            {"https://nl.howrse.com-BridleClassic2", "145"},
            {"https://nl.howrse.com-BridleClassic3", "15"},
            {"https://nl.howrse.com-BridleWestern1", "102"},
            {"https://nl.howrse.com-BridleWestern2", "262"},
            {"https://nl.howrse.com-BridleWestern3", "103"},
            {"https://nl.howrse.com-SaddleClassic1", "11"},
            {"https://nl.howrse.com-SaddleClassic2", "147"},
            {"https://nl.howrse.com-SaddleClassic3", "13"},
            {"https://nl.howrse.com-SaddleWestern1", "99"},
            {"https://nl.howrse.com-SaddleWestern2", "261"},
            {"https://nl.howrse.com-SaddleWestern3", "100"},
            {"https://nl.howrse.com-RampClassic", "349"},
            {"https://nl.howrse.com-RampWestern", "350"},
            {"https://nl.howrse.com-Bandages", "352"},
            {"https://nl.howrse.com-Forehead", "351"},

            {"https://www.howrse.se-BridleClassic1", "14"},
            {"https://www.howrse.se-BridleClassic2", "145"},
            {"https://www.howrse.se-BridleClassic3", "15"},
            {"https://www.howrse.se-BridleWestern1", "102"},
            {"https://www.howrse.se-BridleWestern2", "262"},
            {"https://www.howrse.se-BridleWestern3", "103"},
            {"https://www.howrse.se-SaddleClassic1", "11"},
            {"https://www.howrse.se-SaddleClassic2", "147"},
            {"https://www.howrse.se-SaddleClassic3", "13"},
            {"https://www.howrse.se-SaddleWestern1", "99"},
            {"https://www.howrse.se-SaddleWestern2", "261"},
            {"https://www.howrse.se-SaddleWestern3", "100"},
            {"https://www.howrse.se-RampClassic", "349"},
            {"https://www.howrse.se-RampWestern", "350"},
            {"https://www.howrse.se-Bandages", "352"},
            {"https://www.howrse.se-Forehead", "351"},

            {"https://www.howrse.pl-BridleClassic1", "14"},
            {"https://www.howrse.pl-BridleClassic2", "145"},
            {"https://www.howrse.pl-BridleClassic3", "15"},
            {"https://www.howrse.pl-BridleWestern1", "102"},
            {"https://www.howrse.pl-BridleWestern2", "262"},
            {"https://www.howrse.pl-BridleWestern3", "103"},
            {"https://www.howrse.pl-SaddleClassic1", "11"},
            {"https://www.howrse.pl-SaddleClassic2", "147"},
            {"https://www.howrse.pl-SaddleClassic3", "13"},
            {"https://www.howrse.pl-SaddleWestern1", "99"},
            {"https://www.howrse.pl-SaddleWestern2", "261"},
            {"https://www.howrse.pl-SaddleWestern3", "100"},
            {"https://www.howrse.pl-RampClassic", "349"},
            {"https://www.howrse.pl-RampWestern", "350"},
            {"https://www.howrse.pl-Bandages", "352"},
            {"https://www.howrse.pl-Forehead", "351"},

            {"https://www.howrse.cz-BridleClassic1", "14"},
            {"https://www.howrse.cz-BridleClassic2", "145"},
            {"https://www.howrse.cz-BridleClassic3", "15"},
            {"https://www.howrse.cz-BridleWestern1", "102"},
            {"https://www.howrse.cz-BridleWestern2", "262"},
            {"https://www.howrse.cz-BridleWestern3", "103"},
            {"https://www.howrse.cz-SaddleClassic1", "11"},
            {"https://www.howrse.cz-SaddleClassic2", "147"},
            {"https://www.howrse.cz-SaddleClassic3", "13"},
            {"https://www.howrse.cz-SaddleWestern1", "99"},
            {"https://www.howrse.cz-SaddleWestern2", "261"},
            {"https://www.howrse.cz-SaddleWestern3", "100"},
            {"https://www.howrse.cz-RampClassic", "349"},
            {"https://www.howrse.cz-RampWestern", "350"},
            {"https://www.howrse.cz-Bandages", "352"},
            {"https://www.howrse.cz-Forehead", "351"},

            {"https://www.howrse.dk-BridleClassic1", "14"},
            {"https://www.howrse.dk-BridleClassic2", "145"},
            {"https://www.howrse.dk-BridleClassic3", "15"},
            {"https://www.howrse.dk-BridleWestern1", "102"},
            {"https://www.howrse.dk-BridleWestern2", "262"},
            {"https://www.howrse.dk-BridleWestern3", "103"},
            {"https://www.howrse.dk-SaddleClassic1", "11"},
            {"https://www.howrse.dk-SaddleClassic2", "147"},
            {"https://www.howrse.dk-SaddleClassic3", "13"},
            {"https://www.howrse.dk-SaddleWestern1", "99"},
            {"https://www.howrse.dk-SaddleWestern2", "261"},
            {"https://www.howrse.dk-SaddleWestern3", "100"},
            {"https://www.howrse.dk-RampClassic", "349"},
            {"https://www.howrse.dk-RampWestern", "350"},
            {"https://www.howrse.dk-Bandages", "352"},
            {"https://www.howrse.dk-Forehead", "351"},

            {"https://www.howrse.fi-BridleClassic1", "14"},
            {"https://www.howrse.fi-BridleClassic2", "145"},
            {"https://www.howrse.fi-BridleClassic3", "15"},
            {"https://www.howrse.fi-BridleWestern1", "102"},
            {"https://www.howrse.fi-BridleWestern2", "262"},
            {"https://www.howrse.fi-BridleWestern3", "103"},
            {"https://www.howrse.fi-SaddleClassic1", "11"},
            {"https://www.howrse.fi-SaddleClassic2", "147"},
            {"https://www.howrse.fi-SaddleClassic3", "13"},
            {"https://www.howrse.fi-SaddleWestern1", "99"},
            {"https://www.howrse.fi-SaddleWestern2", "261"},
            {"https://www.howrse.fi-SaddleWestern3", "100"},
            {"https://www.howrse.fi-RampClassic", "349"},
            {"https://www.howrse.fi-RampWestern", "350"},
            {"https://www.howrse.fi-Bandages", "352"},
            {"https://www.howrse.fi-Forehead", "351"},

            {"https://www.howrse.no-BridleClassic1", "14"},
            {"https://www.howrse.no-BridleClassic2", "145"},
            {"https://www.howrse.no-BridleClassic3", "15"},
            {"https://www.howrse.no-BridleWestern1", "102"},
            {"https://www.howrse.no-BridleWestern2", "262"},
            {"https://www.howrse.no-BridleWestern3", "103"},
            {"https://www.howrse.no-SaddleClassic1", "11"},
            {"https://www.howrse.no-SaddleClassic2", "147"},
            {"https://www.howrse.no-SaddleClassic3", "13"},
            {"https://www.howrse.no-SaddleWestern1", "99"},
            {"https://www.howrse.no-SaddleWestern2", "261"},
            {"https://www.howrse.no-SaddleWestern3", "100"},
            {"https://www.howrse.no-RampClassic", "349"},
            {"https://www.howrse.no-RampWestern", "350"},
            {"https://www.howrse.no-Bandages", "352"},
            {"https://www.howrse.no-Forehead", "351"},

            {"https://ar.howrse.com-BridleClassic1", "14"},
            {"https://ar.howrse.com-BridleClassic2", "145"},
            {"https://ar.howrse.com-BridleClassic3", "15"},
            {"https://ar.howrse.com-SaddleClassic1", "11"},
            {"https://ar.howrse.com-SaddleClassic2", "147"},
            {"https://ar.howrse.com-SaddleClassic3", "13"},
            {"https://ar.howrse.com-RampClassic", "328"},
            {"https://ar.howrse.com-Bandages", "331"},
            {"https://ar.howrse.com-Forehead", "330"},

            {"https://www.howrse.hu-BridleClassic1", "14"},
            {"https://www.howrse.hu-BridleClassic2", "145"},
            {"https://www.howrse.hu-BridleClassic3", "15"},
            {"https://www.howrse.hu-BridleWestern1", "102"},
            {"https://www.howrse.hu-BridleWestern2", "262"},
            {"https://www.howrse.hu-BridleWestern3", "103"},
            {"https://www.howrse.hu-SaddleClassic1", "11"},
            {"https://www.howrse.hu-SaddleClassic2", "147"},
            {"https://www.howrse.hu-SaddleClassic3", "13"},
            {"https://www.howrse.hu-SaddleWestern1", "99"},
            {"https://www.howrse.hu-SaddleWestern2", "261"},
            {"https://www.howrse.hu-SaddleWestern3", "100"},
            {"https://www.howrse.hu-RampClassic", "349"},
            {"https://www.howrse.hu-RampWestern", "350"},
            {"https://www.howrse.hu-Bandages", "352"},
            {"https://www.howrse.hu-Forehead", "351"},

            {"https://www.howrse.ro-BridleClassic1", "14"},
            {"https://www.howrse.ro-BridleClassic2", "145"},
            {"https://www.howrse.ro-BridleClassic3", "15"},
            {"https://www.howrse.ro-BridleWestern1", "102"},
            {"https://www.howrse.ro-BridleWestern2", "262"},
            {"https://www.howrse.ro-BridleWestern3", "103"},
            {"https://www.howrse.ro-SaddleClassic1", "11"},
            {"https://www.howrse.ro-SaddleClassic2", "147"},
            {"https://www.howrse.ro-SaddleClassic3", "13"},
            {"https://www.howrse.ro-SaddleWestern1", "99"},
            {"https://www.howrse.ro-SaddleWestern2", "261"},
            {"https://www.howrse.ro-SaddleWestern3", "100"},
            {"https://www.howrse.ro-RampClassic", "349"},
            {"https://www.howrse.ro-RampWestern", "350"},
            {"https://www.howrse.ro-Bandages", "352"},
            {"https://www.howrse.ro-Forehead", "351"},

            {"https://www.howrse.bg-BridleClassic1", "14"},
            {"https://www.howrse.bg-BridleClassic2", "145"},
            {"https://www.howrse.bg-BridleClassic3", "15"},
            {"https://www.howrse.bg-BridleWestern1", "102"},
            {"https://www.howrse.bg-BridleWestern2", "262"},
            {"https://www.howrse.bg-BridleWestern3", "103"},
            {"https://www.howrse.bg-SaddleClassic1", "11"},
            {"https://www.howrse.bg-SaddleClassic2", "147"},
            {"https://www.howrse.bg-SaddleClassic3", "13"},
            {"https://www.howrse.bg-SaddleWestern1", "99"},
            {"https://www.howrse.bg-SaddleWestern2", "261"},
            {"https://www.howrse.bg-SaddleWestern3", "100"},
            {"https://www.howrse.bg-RampClassic", "349"},
            {"https://www.howrse.bg-RampWestern", "350"},
            {"https://www.howrse.bg-Bandages", "352"},
            {"https://www.howrse.bg-Forehead", "351"},

            {"https://www.howrse.si-BridleClassic1", "14"},
            {"https://www.howrse.si-BridleClassic2", "145"},
            {"https://www.howrse.si-BridleClassic3", "15"},
            {"https://www.howrse.si-SaddleClassic1", "11"},
            {"https://www.howrse.si-SaddleClassic2", "147"},
            {"https://www.howrse.si-SaddleClassic3", "13"},
            {"https://www.howrse.si-RampClassic", "349"},
            {"https://www.howrse.si-Bandages", "352"},
            {"https://www.howrse.si-Forehead", "351"},

            {"https://www.howrse.sk-BridleClassic1", "14"},
            {"https://www.howrse.sk-BridleClassic2", "145"},
            {"https://www.howrse.sk-BridleClassic3", "15"},
            {"https://www.howrse.sk-SaddleClassic1", "11"},
            {"https://www.howrse.sk-SaddleClassic2", "147"},
            {"https://www.howrse.sk-SaddleClassic3", "13"},
            {"https://www.howrse.sk-RampClassic", "349"},
            {"https://www.howrse.sk-Bandages", "352"},
            {"https://www.howrse.sk-Forehead", "351"},
        };

        public EquipmentType Type { get; set; }
        public string Id { get; set; }
        public int Amount { get; set; }
        public int Price { get; private set; }

        public Equipment(string baseAddress, EquipmentType type, int price)
        {
            Type = type;
            Price = price;
            try
            {
                Id = ids[$"{baseAddress}-{Enum.GetName(typeof(EquipmentType), type)}"];
            } catch
            {
                Id = "0";
            }
        }
    }
}
