//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotQually.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotQually.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на окончен; ОР добавлено:.
        /// </summary>
        public static string AccountNotificationEndMessage {
            get {
                return ResourceManager.GetString("AccountNotificationEndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество аккаунтов.
        /// </summary>
        public static string AccountNum {
            get {
                return ResourceManager.GetString("AccountNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (соу).
        /// </summary>
        public static string AccTypeString {
            get {
                return ResourceManager.GetString("AccTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Яблоки.
        /// </summary>
        public static string Apples {
            get {
                return ResourceManager.GetString("Apples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Морковь.
        /// </summary>
        public static string Carrot {
            get {
                return ResourceManager.GetString("Carrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        public static string ClientNew {
            get {
                return ResourceManager.GetString("ClientNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старый.
        /// </summary>
        public static string ClientOld {
            get {
                return ResourceManager.GetString("ClientOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на обнаружено сниженое здоровье более чем на 50 лошадях!.
        /// </summary>
        public static string FarmNotificationWarnining {
            get {
                return ResourceManager.GetString("FarmNotificationWarnining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аарен,Абагэйл,Абагэйль,Аббай,Аббей,Абби,Аббигаель,Аббигаиль,Аббигайл,Аббигаэль,Аббигейл,Аббигейль,Аббигэйл,Абегэйл,Абелла,Абигайл,Абигаэль,Абигол,Абигэйл,Абигэйль,Абиджил,Абичэйл,Абэйгаэль,Абэйгил,Ава,Авалайн,Авалина,Авалон,Авалона,Авелина,Аверилл,Агава,Агата,Аггай,Агджи,Агджая,Агнес,Агнус,Ада,Адайн,Адамайн,Адамина,Адаминна,Адди,Аддисон,Адела,Аделаида,Аделайн,Адели,Аделина,Аделис,Аделисия,Аделия,Аделл,Аделфа,Адель,Адена,Адин,Адисон,Адиссон,Адмиранда,Адоллина,Адреа,Адри,Адриа,Адриан,Адриана,Адрианн,Адрианна, [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лен.
        /// </summary>
        public static string Flax {
            get {
                return ResourceManager.GetString("Flax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фураж.
        /// </summary>
        public static string Hay {
            get {
                return ResourceManager.GetString("Hay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кожа.
        /// </summary>
        public static string Leather {
            get {
                return ResourceManager.GetString("Leather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти в соу.
        /// </summary>
        public static string LoginCoConverter {
            get {
                return ResourceManager.GetString("LoginCoConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке соу аккаунтов!.
        /// </summary>
        public static string LoginCoLoadErroMessage {
            get {
                return ResourceManager.GetString("LoginCoLoadErroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при входе в соу!.
        /// </summary>
        public static string LoginCoLoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginCoLoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string LoginCoPageCancelBtn {
            get {
                return ResourceManager.GetString("LoginCoPageCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string LoginCoPageLoginBtn {
            get {
                return ResourceManager.GetString("LoginCoPageLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружена проблема с файлом аккаунтов, файл будет перезаписан..
        /// </summary>
        public static string LoginErrorLoadFileMessage {
            get {
                return ResourceManager.GetString("LoginErrorLoadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось войти в соу!.
        /// </summary>
        public static string LoginErrorLoginCoMessage {
            get {
                return ResourceManager.GetString("LoginErrorLoginCoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка входа!.
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить.
        /// </summary>
        public static string LoginPageClearBtn {
            get {
                return ResourceManager.GetString("LoginPageClearBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string LoginPageDeleteBtn {
            get {
                return ResourceManager.GetString("LoginPageDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string LoginPageLoginBtn {
            get {
                return ResourceManager.GetString("LoginPageLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string LoginPageLoginText {
            get {
                return ResourceManager.GetString("LoginPageLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string LoginPagePasswordText {
            get {
                return ResourceManager.GetString("LoginPagePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string LoginPageProxyLoginText {
            get {
                return ResourceManager.GetString("LoginPageProxyLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string LoginPageProxyPasswordText {
            get {
                return ResourceManager.GetString("LoginPageProxyPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прокси.
        /// </summary>
        public static string LoginPageProxyText {
            get {
                return ResourceManager.GetString("LoginPageProxyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить данные.
        /// </summary>
        public static string LoginPageRememberChk {
            get {
                return ResourceManager.GetString("LoginPageRememberChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранненые аккаунты.
        /// </summary>
        public static string LoginPageSavedAccountsText {
            get {
                return ResourceManager.GetString("LoginPageSavedAccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер.
        /// </summary>
        public static string LoginPageServerText {
            get {
                return ResourceManager.GetString("LoginPageServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon logo2 {
            get {
                object obj = ResourceManager.GetObject("logo2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти из соу.
        /// </summary>
        public static string LogoffCoConverter {
            get {
                return ResourceManager.GetString("LogoffCoConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт.
        /// </summary>
        public static string MainAccountTextMessage {
            get {
                return ResourceManager.GetString("MainAccountTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не был выбран завод или аккаунт находится в состоянии прогона!.
        /// </summary>
        public static string MainAddFarmError {
            get {
                return ResourceManager.GetString("MainAddFarmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт находится в состоянии прогона!.
        /// </summary>
        public static string MainClearFarmsError {
            get {
                return ResourceManager.GetString("MainClearFarmsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный аккаунт находится в состоянии прогона!.
        /// </summary>
        public static string MainDeleteAccError1 {
            get {
                return ResourceManager.GetString("MainDeleteAccError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалять аккаунты в состоянии прогона!.
        /// </summary>
        public static string MainDeleteAccError2 {
            get {
                return ResourceManager.GetString("MainDeleteAccError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не был выбран аккаунт!.
        /// </summary>
        public static string MainDeleteAccError3 {
            get {
                return ResourceManager.GetString("MainDeleteAccError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не был выбран завод или аккаунт находится в состоянии прогона!.
        /// </summary>
        public static string MainDeleteFarmError {
            get {
                return ResourceManager.GetString("MainDeleteFarmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завод.
        /// </summary>
        public static string MainFarmTextMessage {
            get {
                return ResourceManager.GetString("MainFarmTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лошадь.
        /// </summary>
        public static string MainHorseTextMessage {
            get {
                return ResourceManager.GetString("MainHorseTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось войти в соу.
        /// </summary>
        public static string MainLoadAccErrorMessage1 {
            get {
                return ResourceManager.GetString("MainLoadAccErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при загрузке аккаунтов!.
        /// </summary>
        public static string MainLoadAccErrorMessage2 {
            get {
                return ResourceManager.GetString("MainLoadAccErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки файла! Файлы можно использовать только те, которые были созданы этой версией!.
        /// </summary>
        public static string MainLoadAccErrorMessage3 {
            get {
                return ResourceManager.GetString("MainLoadAccErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не был выбран аккаунт или аккаунт находится в состоянии прогона!.
        /// </summary>
        public static string MainLoginCoErrorMessage {
            get {
                return ResourceManager.GetString("MainLoginCoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интернет.
        /// </summary>
        public static string MainMenuInternetText {
            get {
                return ResourceManager.GetString("MainMenuInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим работы.
        /// </summary>
        public static string MainMenuModeText {
            get {
                return ResourceManager.GetString("MainMenuModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомления вместо окон.
        /// </summary>
        public static string MainMenuNotificationsChk {
            get {
                return ResourceManager.GetString("MainMenuNotificationsChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параллельные лошади.
        /// </summary>
        public static string MainMenuParallelHorsesChk {
            get {
                return ResourceManager.GetString("MainMenuParallelHorsesChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случайные паузы.
        /// </summary>
        public static string MainMenuRandomPausesChk {
            get {
                return ResourceManager.GetString("MainMenuRandomPausesChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка.
        /// </summary>
        public static string MainMenuSortText {
            get {
                return ResourceManager.GetString("MainMenuSortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сворачивать в трей.
        /// </summary>
        public static string MainMenuTrayChk {
            get {
                return ResourceManager.GetString("MainMenuTrayChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт.
        /// </summary>
        public static string MainNotificationAccountMessage {
            get {
                return ResourceManager.GetString("MainNotificationAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string MainNotificationCancelMessage {
            get {
                return ResourceManager.GetString("MainNotificationCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окончен прогон по очереди.
        /// </summary>
        public static string MainNotificationEndWorkMessage {
            get {
                return ResourceManager.GetString("MainNotificationEndWorkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string MainNotificationErrorMessage {
            get {
                return ResourceManager.GetString("MainNotificationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завод.
        /// </summary>
        public static string MainNotificationFarmMessage {
            get {
                return ResourceManager.GetString("MainNotificationFarmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лошадь.
        /// </summary>
        public static string MainNotificationHorseMessage {
            get {
                return ResourceManager.GetString("MainNotificationHorseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не был выбран аккаунт!.
        /// </summary>
        public static string MainOpenManagmentErrorMessage {
            get {
                return ResourceManager.GetString("MainOpenManagmentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не был выбран аккаунт!.
        /// </summary>
        public static string MainOpenSettingsErrorMessage {
            get {
                return ResourceManager.GetString("MainOpenSettingsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление аккаунтом.
        /// </summary>
        public static string MainPageAccManagmentBtn {
            get {
                return ResourceManager.GetString("MainPageAccManagmentBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить аккаунт.
        /// </summary>
        public static string MainPageAddAccBtn {
            get {
                return ResourceManager.GetString("MainPageAddAccBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить аккаунт.
        /// </summary>
        public static string MainPageDeleteAccBtn {
            get {
                return ResourceManager.GetString("MainPageDeleteAccBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экю.
        /// </summary>
        public static string MainPageEquText {
            get {
                return ResourceManager.GetString("MainPageEquText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заводы.
        /// </summary>
        public static string MainPageFarmsText {
            get {
                return ResourceManager.GetString("MainPageFarmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фураж.
        /// </summary>
        public static string MainPageHayText {
            get {
                return ResourceManager.GetString("MainPageHayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить список аккаунтов.
        /// </summary>
        public static string MainPageLoadAccListBtn {
            get {
                return ResourceManager.GetString("MainPageLoadAccListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти в соу.
        /// </summary>
        public static string MainPageLoginCoBtn {
            get {
                return ResourceManager.GetString("MainPageLoginCoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим.
        /// </summary>
        public static string MainPageModeText {
            get {
                return ResourceManager.GetString("MainPageModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string MainPageNameText {
            get {
                return ResourceManager.GetString("MainPageNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Овес.
        /// </summary>
        public static string MainPageOatText {
            get {
                return ResourceManager.GetString("MainPageOatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть статус.
        /// </summary>
        public static string MainPageOpenStatusBtn {
            get {
                return ResourceManager.GetString("MainPageOpenStatusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОР.
        /// </summary>
        public static string MainPageORText {
            get {
                return ResourceManager.GetString("MainPageORText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропуски.
        /// </summary>
        public static string MainPagePassText {
            get {
                return ResourceManager.GetString("MainPagePassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить список аккаунтов.
        /// </summary>
        public static string MainPageSaveAccListBtn {
            get {
                return ResourceManager.GetString("MainPageSaveAccListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить соу.
        /// </summary>
        public static string MainPageSaveCoBtn {
            get {
                return ResourceManager.GetString("MainPageSaveCoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string MainPageSettingsBtn {
            get {
                return ResourceManager.GetString("MainPageSettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навоз.
        /// </summary>
        public static string MainPageShitText {
            get {
                return ResourceManager.GetString("MainPageShitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очередь.
        /// </summary>
        public static string MainPageStackText {
            get {
                return ResourceManager.GetString("MainPageStackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогнать все.
        /// </summary>
        public static string MainPageStartAllBtn {
            get {
                return ResourceManager.GetString("MainPageStartAllBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогнать.
        /// </summary>
        public static string MainPageStartBtn {
            get {
                return ResourceManager.GetString("MainPageStartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить все.
        /// </summary>
        public static string MainPageStopAllBtn {
            get {
                return ResourceManager.GetString("MainPageStopAllBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить.
        /// </summary>
        public static string MainPageStopBtn {
            get {
                return ResourceManager.GetString("MainPageStopBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия:.
        /// </summary>
        public static string MainPageVersionText {
            get {
                return ResourceManager.GetString("MainPageVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отменен.
        /// </summary>
        public static string MainProgressCancelMessage {
            get {
                return ResourceManager.GetString("MainProgressCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка.
        /// </summary>
        public static string MainProgressErrorMessage {
            get {
                return ResourceManager.GetString("MainProgressErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный аккаунт не соу!.
        /// </summary>
        public static string MainSaveCoAccErrorMessage {
            get {
                return ResourceManager.GetString("MainSaveCoAccErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт сохранен!.
        /// </summary>
        public static string MainSaveCoAccMessage {
            get {
                return ResourceManager.GetString("MainSaveCoAccMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас включен режим прогона по очереди! Действия по этой кнопке производиться не будут!.
        /// </summary>
        public static string MainStartAllErrorMessage {
            get {
                return ResourceManager.GetString("MainStartAllErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменено.
        /// </summary>
        public static string MainStoppedWorkMessage {
            get {
                return ResourceManager.GetString("MainStoppedWorkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Во время прогона произошла ошибка! Все необходимые данные были записаны. Не забудьте отправить отчет..
        /// </summary>
        public static string MainWorkErrorMessage {
            get {
                return ResourceManager.GetString("MainWorkErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ааран,Аарен,Ааррон,Аб,Аббат,Абботт,Абей,Абелл,Абель,Абнар,Абнер,Абнор,Абот,Аботт,Абрам,Абран,Абрахам,Абсалон,Аверилл,Адам,Аддам,Аддисон,Аден,Адисон,Адиссон,Адлэй,Адней,Адольф,Адриан,Адэйр,Адэр,Азия,Азэлстан,Айбл,Айзек,Айк,Ак,Акей,Акерлеа,Акерлей,Акерли,Аки,Аклеа,Аклей,Акли,Актон,Акэль,Алан,Аластеир,Аластэйр,Алвар,Алвен,Алви,Алвин,Алвис,Алгар,Алджернон,Алеистер,Алек,Алекс,Александр,Ален,Алестер,Алжир,Алик,Аликс,Алисандр,Алисдэйр,Алиссандр,Алистер,Алистэйр,Аллан,Аллен,Аллин,Аллистер,Аллистир,Аллистэйр,Алтон,А [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при покупке!.
        /// </summary>
        public static string ManagmentBuyErrorMessage {
            get {
                return ResourceManager.GetString("ManagmentBuyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Яблоки.
        /// </summary>
        public static string ManagmentPageApple {
            get {
                return ResourceManager.GetString("ManagmentPageApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купить.
        /// </summary>
        public static string ManagmentPageBuyBtn {
            get {
                return ResourceManager.GetString("ManagmentPageBuyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Морковь.
        /// </summary>
        public static string ManagmentPageCarrot {
            get {
                return ResourceManager.GetString("ManagmentPageCarrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экю.
        /// </summary>
        public static string ManagmentPageEqu {
            get {
                return ResourceManager.GetString("ManagmentPageEqu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лен.
        /// </summary>
        public static string ManagmentPageFlax {
            get {
                return ResourceManager.GetString("ManagmentPageFlax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фураж.
        /// </summary>
        public static string ManagmentPageHay {
            get {
                return ResourceManager.GetString("ManagmentPageHay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кожа.
        /// </summary>
        public static string ManagmentPageLeather {
            get {
                return ResourceManager.GetString("ManagmentPageLeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Овес.
        /// </summary>
        public static string ManagmentPageOat {
            get {
                return ResourceManager.GetString("ManagmentPageOat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string ManagmentPageReturnBtn {
            get {
                return ResourceManager.GetString("ManagmentPageReturnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Песок.
        /// </summary>
        public static string ManagmentPageSand {
            get {
                return ResourceManager.GetString("ManagmentPageSand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продать.
        /// </summary>
        public static string ManagmentPageSellBtn {
            get {
                return ResourceManager.GetString("ManagmentPageSellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навоз.
        /// </summary>
        public static string ManagmentPageShit {
            get {
                return ResourceManager.GetString("ManagmentPageShit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Железо.
        /// </summary>
        public static string ManagmentPageSteel {
            get {
                return ResourceManager.GetString("ManagmentPageSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Солома.
        /// </summary>
        public static string ManagmentPageStraw {
            get {
                return ResourceManager.GetString("ManagmentPageStraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пшеница.
        /// </summary>
        public static string ManagmentPageWheat {
            get {
                return ResourceManager.GetString("ManagmentPageWheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дерево.
        /// </summary>
        public static string ManagmentPageWood {
            get {
                return ResourceManager.GetString("ManagmentPageWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при продаже!.
        /// </summary>
        public static string ManagmentSellErrorMessage {
            get {
                return ResourceManager.GetString("ManagmentSellErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очередь с одинаковыми настройками.
        /// </summary>
        public static string ModeGlobalOrder {
            get {
                return ResourceManager.GetString("ModeGlobalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параллельно с одинаковыми настройками.
        /// </summary>
        public static string ModeGlobalParallel {
            get {
                return ResourceManager.GetString("ModeGlobalParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очередь с разными настройками.
        /// </summary>
        public static string ModeSingleOrder {
            get {
                return ResourceManager.GetString("ModeSingleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параллельно с разными настройками.
        /// </summary>
        public static string ModeSingleParallel {
            get {
                return ResourceManager.GetString("ModeSingleParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не продавать.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Овес.
        /// </summary>
        public static string Oat {
            get {
                return ResourceManager.GetString("Oat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОР.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка отправки отчета.
        /// </summary>
        public static string ReportErrorMessage {
            get {
                return ResourceManager.GetString("ReportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение отправлено!.
        /// </summary>
        public static string ReportMessage {
            get {
                return ResourceManager.GetString("ReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты (страница вк/почта).
        /// </summary>
        public static string ReportPageContactsText {
            get {
                return ResourceManager.GetString("ReportPageContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        public static string ReportPageMessageText {
            get {
                return ResourceManager.GetString("ReportPageMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string ReportPageReturnBtn {
            get {
                return ResourceManager.GetString("ReportPageReturnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string ReportPageSendBtn {
            get {
                return ResourceManager.GetString("ReportPageSendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Песок.
        /// </summary>
        public static string Sand {
            get {
                return ResourceManager.GetString("Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Арабский.
        /// </summary>
        public static string ServerArabic {
            get {
                return ResourceManager.GetString("ServerArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Австралия.
        /// </summary>
        public static string ServerAustralia {
            get {
                return ResourceManager.GetString("ServerAustralia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Болгария.
        /// </summary>
        public static string ServerBulgaria {
            get {
                return ResourceManager.GetString("ServerBulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канада.
        /// </summary>
        public static string ServerCanada {
            get {
                return ResourceManager.GetString("ServerCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Англия.
        /// </summary>
        public static string ServerEngland {
            get {
                return ResourceManager.GetString("ServerEngland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Франция Gaia.
        /// </summary>
        public static string ServerFranceGaia {
            get {
                return ResourceManager.GetString("ServerFranceGaia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Франция Ouranos.
        /// </summary>
        public static string ServerFranceOuranos {
            get {
                return ResourceManager.GetString("ServerFranceOuranos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Немецкий.
        /// </summary>
        public static string ServerGermany {
            get {
                return ResourceManager.GetString("ServerGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интернациональный.
        /// </summary>
        public static string ServerInternational {
            get {
                return ResourceManager.GetString("ServerInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Норвегия.
        /// </summary>
        public static string ServerNorway {
            get {
                return ResourceManager.GetString("ServerNorway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Польша.
        /// </summary>
        public static string ServerPoland {
            get {
                return ResourceManager.GetString("ServerPoland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Румыния.
        /// </summary>
        public static string ServerRomain {
            get {
                return ResourceManager.GetString("ServerRomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Россия.
        /// </summary>
        public static string ServerRussia {
            get {
                return ResourceManager.GetString("ServerRussia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испания.
        /// </summary>
        public static string ServerSpain {
            get {
                return ResourceManager.GetString("ServerSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Швеция.
        /// </summary>
        public static string ServerSweden {
            get {
                return ResourceManager.GetString("ServerSweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на США.
        /// </summary>
        public static string ServerUSA {
            get {
                return ResourceManager.GetString("ServerUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string SettingsPageAcceptBtn {
            get {
                return ResourceManager.GetString("SettingsPageAcceptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аффикс.
        /// </summary>
        public static string SettingsPageAffixText {
            get {
                return ResourceManager.GetString("SettingsPageAffixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие.
        /// </summary>
        public static string SettingsPageAllText {
            get {
                return ResourceManager.GetString("SettingsPageAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогон жеребят.
        /// </summary>
        public static string SettingsPageBabiesChk {
            get {
                return ResourceManager.GetString("SettingsPageBabiesChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жеребята.
        /// </summary>
        public static string SettingsPageBabiesText {
            get {
                return ResourceManager.GetString("SettingsPageBabiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена до.
        /// </summary>
        public static string SettingsPageBuyBelowText {
            get {
                return ResourceManager.GetString("SettingsPageBuyBelowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупка/Продажа.
        /// </summary>
        public static string SettingsPageBuySellText {
            get {
                return ResourceManager.GetString("SettingsPageBuySellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупать пшеницу.
        /// </summary>
        public static string SettingsPageBuyWheatChk {
            get {
                return ResourceManager.GetString("SettingsPageBuyWheatChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Морковь.
        /// </summary>
        public static string SettingsPageCarrotChk {
            get {
                return ResourceManager.GetString("SettingsPageCarrotChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КСК.
        /// </summary>
        public static string SettingsPageCenterText {
            get {
                return ResourceManager.GetString("SettingsPageCenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чистокровные.
        /// </summary>
        public static string SettingsPageCleanBloodChk {
            get {
                return ResourceManager.GetString("SettingsPageCleanBloodChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продлевать.
        /// </summary>
        public static string SettingsPageContinueChk {
            get {
                return ResourceManager.GetString("SettingsPageContinueChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дозапись в общие.
        /// </summary>
        public static string SettingsPageContinueToAllChk {
            get {
                return ResourceManager.GetString("SettingsPageContinueToAllChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заводчик.
        /// </summary>
        public static string SettingsPageFarmerText {
            get {
                return ResourceManager.GetString("SettingsPageFarmerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завод.
        /// </summary>
        public static string SettingsPageFarmText {
            get {
                return ResourceManager.GetString("SettingsPageFarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя жен.
        /// </summary>
        public static string SettingsPageFemaleNameText {
            get {
                return ResourceManager.GetString("SettingsPageFemaleNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогон.
        /// </summary>
        public static string SettingsPageGoText {
            get {
                return ResourceManager.GetString("SettingsPageGoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГП до:.
        /// </summary>
        public static string SettingsPageGPBelowText {
            get {
                return ResourceManager.GetString("SettingsPageGPBelowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во фуража.
        /// </summary>
        public static string SettingsPageHayQuanText {
            get {
                return ResourceManager.GetString("SettingsPageHayQuanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случки жен.
        /// </summary>
        public static string SettingsPageHorsingFemaleText {
            get {
                return ResourceManager.GetString("SettingsPageHorsingFemaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случки Жен.
        /// </summary>
        public static string SettingsPageHorsingFemaleText2 {
            get {
                return ResourceManager.GetString("SettingsPageHorsingFemaleText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случки Муж.
        /// </summary>
        public static string SettingsPageHorsingMaleText {
            get {
                return ResourceManager.GetString("SettingsPageHorsingMaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порог здоровья.
        /// </summary>
        public static string SettingsPageHPLimitText {
            get {
                return ResourceManager.GetString("SettingsPageHPLimitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить из файла.
        /// </summary>
        public static string SettingsPageLoadBtn {
            get {
                return ResourceManager.GetString("SettingsPageLoadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружать спящих.
        /// </summary>
        public static string SettingsPageLoadSleepChk {
            get {
                return ResourceManager.GetString("SettingsPageLoadSleepChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя муж.
        /// </summary>
        public static string SettingsPageMaleNameText {
            get {
                return ResourceManager.GetString("SettingsPageMaleNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Миссия.
        /// </summary>
        public static string SettingsPageMissionChk {
            get {
                return ResourceManager.GetString("SettingsPageMissionChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Миссия после 28.
        /// </summary>
        public static string SettingsPageMissionOldChk {
            get {
                return ResourceManager.GetString("SettingsPageMissionOldChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во овса.
        /// </summary>
        public static string SettingsPageOatQuanText {
            get {
                return ResourceManager.GetString("SettingsPageOatQuanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогон лошади за 30.
        /// </summary>
        public static string SettingsPageOldHorseChk {
            get {
                return ResourceManager.GetString("SettingsPageOldHorseChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string SettingsPagePriceText {
            get {
                return ResourceManager.GetString("SettingsPagePriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случайные имена.
        /// </summary>
        public static string SettingsPageRandomNamesChk {
            get {
                return ResourceManager.GetString("SettingsPageRandomNamesChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить.
        /// </summary>
        public static string SettingsPageRefreshBtn {
            get {
                return ResourceManager.GetString("SettingsPageRefreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резерв.
        /// </summary>
        public static string SettingsPageReserveText {
            get {
                return ResourceManager.GetString("SettingsPageReserveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string SettingsPageReturnBtn {
            get {
                return ResourceManager.GetString("SettingsPageReturnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить в файл.
        /// </summary>
        public static string SettingsPageSaveBtn {
            get {
                return ResourceManager.GetString("SettingsPageSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свой.
        /// </summary>
        public static string SettingsPageSelfChk {
            get {
                return ResourceManager.GetString("SettingsPageSelfChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свои жеребцы.
        /// </summary>
        public static string SettingsPageSelfMaleChk {
            get {
                return ResourceManager.GetString("SettingsPageSelfMaleChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажа основной.
        /// </summary>
        public static string SettingsPageSellMainText {
            get {
                return ResourceManager.GetString("SettingsPageSellMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продавать навоз.
        /// </summary>
        public static string SettingsPageSellShitChk {
            get {
                return ResourceManager.GetString("SettingsPageSellShitChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажа запасной.
        /// </summary>
        public static string SettingsPageSellSubText {
            get {
                return ResourceManager.GetString("SettingsPageSellSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинать с.
        /// </summary>
        public static string SettingsPageStartWithText {
            get {
                return ResourceManager.GetString("SettingsPageStartWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ласка.
        /// </summary>
        public static string SettingsPageStrokeChk {
            get {
                return ResourceManager.GetString("SettingsPageStrokeChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Командные.
        /// </summary>
        public static string SettingsPageTeamChk {
            get {
                return ResourceManager.GetString("SettingsPageTeamChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В команду.
        /// </summary>
        public static string SettingsPageToTeamChk {
            get {
                return ResourceManager.GetString("SettingsPageToTeamChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включать соу при выходе.
        /// </summary>
        public static string SettingsPageTurnOnCoChk {
            get {
                return ResourceManager.GetString("SettingsPageTurnOnCoChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкл/Выкл.
        /// </summary>
        public static string SettingsPageTurnOnFemaleChk {
            get {
                return ResourceManager.GetString("SettingsPageTurnOnFemaleChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкл/Выкл.
        /// </summary>
        public static string SettingsPageTurnOnMaleChk {
            get {
                return ResourceManager.GetString("SettingsPageTurnOnMaleChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С фуражом.
        /// </summary>
        public static string SettingsPageWithHayChk {
            get {
                return ResourceManager.GetString("SettingsPageWithHayChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С овсом.
        /// </summary>
        public static string SettingsPageWithOatChk {
            get {
                return ResourceManager.GetString("SettingsPageWithOatChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навоз.
        /// </summary>
        public static string Shit {
            get {
                return ResourceManager.GetString("Shit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст.
        /// </summary>
        public static string SortAge {
            get {
                return ResourceManager.GetString("SortAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения.
        /// </summary>
        public static string SortDate {
            get {
                return ResourceManager.GetString("SortDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string SortName {
            get {
                return ResourceManager.GetString("SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Генетический потенциал.
        /// </summary>
        public static string SortPG {
            get {
                return ResourceManager.GetString("SortPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порода.
        /// </summary>
        public static string SortRace {
            get {
                return ResourceManager.GetString("SortRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навыки.
        /// </summary>
        public static string SortSkills {
            get {
                return ResourceManager.GetString("SortSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Во время прогона.
        /// </summary>
        public static string StartAllErrorMessage1 {
            get {
                return ResourceManager.GetString("StartAllErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на произошла ошибка! Завод.
        /// </summary>
        public static string StartAllErrorMessage2 {
            get {
                return ResourceManager.GetString("StartAllErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все необходимые данные были записаны. Не забудьте отправить отчет..
        /// </summary>
        public static string StartAllErrorMessage3 {
            get {
                return ResourceManager.GetString("StartAllErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт.
        /// </summary>
        public static string StatusPageAccountText {
            get {
                return ResourceManager.GetString("StatusPageAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во оконченных аккаунтов.
        /// </summary>
        public static string StatusPageDoneAccsText {
            get {
                return ResourceManager.GetString("StatusPageDoneAccsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экю.
        /// </summary>
        public static string StatusPageEquText {
            get {
                return ResourceManager.GetString("StatusPageEquText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завод.
        /// </summary>
        public static string StatusPageFarmText {
            get {
                return ResourceManager.GetString("StatusPageFarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фураж.
        /// </summary>
        public static string StatusPageHayText {
            get {
                return ResourceManager.GetString("StatusPageHayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомления.
        /// </summary>
        public static string StatusPageNotificationsText {
            get {
                return ResourceManager.GetString("StatusPageNotificationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Овес.
        /// </summary>
        public static string StatusPageOatText {
            get {
                return ResourceManager.GetString("StatusPageOatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОР.
        /// </summary>
        public static string StatusPageORText {
            get {
                return ResourceManager.GetString("StatusPageORText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогресс.
        /// </summary>
        public static string StatusPageProgressText {
            get {
                return ResourceManager.GetString("StatusPageProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string StatusPageReturnBtn {
            get {
                return ResourceManager.GetString("StatusPageReturnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навоз.
        /// </summary>
        public static string StatusPageShitText {
            get {
                return ResourceManager.GetString("StatusPageShitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во прогоняемых аккаунтов.
        /// </summary>
        public static string StatusPageWorkingAccsText {
            get {
                return ResourceManager.GetString("StatusPageWorkingAccsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Железо.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Солома.
        /// </summary>
        public static string Straw {
            get {
                return ResourceManager.GetString("Straw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пшеница.
        /// </summary>
        public static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла какая-то ошибка! Обратитесь к администрации!.
        /// </summary>
        public static string WindowErrorMessage1 {
            get {
                return ResourceManager.GetString("WindowErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружена попытка несанкционированого доступа!.
        /// </summary>
        public static string WindowErrorMessage2 {
            get {
                return ResourceManager.GetString("WindowErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша подписка не активна или не соотвествует уровень!.
        /// </summary>
        public static string WindowErrorMessage3 {
            get {
                return ResourceManager.GetString("WindowErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно обновление.
        /// </summary>
        public static string WindowMessage {
            get {
                return ResourceManager.GetString("WindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустите лаунчер чтобы обновиться..
        /// </summary>
        public static string WindowMessage1 {
            get {
                return ResourceManager.GetString("WindowMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дерево.
        /// </summary>
        public static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
    }
}
