//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuallyFlash.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuallyFlash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа была остановлена! Исчерпан лимит случек для тяжеловозов!.
        /// </summary>
        public static string AccountHorsingStopMessage {
            get {
                return ResourceManager.GetString("AccountHorsingStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Была выбрана выписка из кск, но не стоит свой резерв кск! Выберите необходимые настройки!.
        /// </summary>
        public static string AccountMessage1 {
            get {
                return ResourceManager.GetString("AccountMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На аккаунте.
        /// </summary>
        public static string AccountOutOfResourcesMessage1 {
            get {
                return ResourceManager.GetString("AccountOutOfResourcesMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на закончилось экю и нет ресурсов для пополнения (или не выбраны для докупки)! Пополните запасы и нажмите ОК.
        /// </summary>
        public static string AccountOutOfResourcesMessage2 {
            get {
                return ResourceManager.GetString("AccountOutOfResourcesMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на закончился фураж и не стоит докупка! Пополните запасы и нажмите ОК.
        /// </summary>
        public static string AccountOutOfResourcesMessage3 {
            get {
                return ResourceManager.GetString("AccountOutOfResourcesMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа была остановлена! Лошадь находится в неверном периоде! Нельзя запускать лошадь, если ей осталось 4 месяца до родов (время, когда соревнования выключены)!.
        /// </summary>
        public static string AccountStopMessage {
            get {
                return ResourceManager.GetString("AccountStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа была остановлена! Был поставлен свой резерв, но лошадь уже записана в какой-то кск!.
        /// </summary>
        public static string AccountStopMessage1 {
            get {
                return ResourceManager.GetString("AccountStopMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа была остановлена! Не удалось выключить автотренировки/автопрогулки! Выключите вручную!.
        /// </summary>
        public static string AccountStopMessage2 {
            get {
                return ResourceManager.GetString("AccountStopMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Яблоки.
        /// </summary>
        public static string Apples {
            get {
                return ResourceManager.GetString("Apples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Морковь.
        /// </summary>
        public static string Carrot {
            get {
                return ResourceManager.GetString("Carrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (соу).
        /// </summary>
        public static string CoPostfix {
            get {
                return ResourceManager.GetString("CoPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аарен,Абагэйл,Абагэйль,Аббай,Аббей,Абби,Аббигаель,Аббигаиль,Аббигайл,Аббигаэль,Аббигейл,Аббигейль,Аббигэйл,Абегэйл,Абелла,Абигайл,Абигаэль,Абигол,Абигэйл,Абигэйль,Абиджил,Абичэйл,Абэйгаэль,Абэйгил,Ава,Авалайн,Авалина,Авалон,Авалона,Авелина,Аверилл,Агава,Агата,Аггай,Агджи,Агджая,Агнес,Агнус,Ада,Адайн,Адамайн,Адамина,Адаминна,Адди,Аддисон,Адела,Аделаида,Аделайн,Адели,Аделина,Аделис,Аделисия,Аделия,Аделл,Аделфа,Адель,Адена,Адин,Адисон,Адиссон,Адмиранда,Адоллина,Адреа,Адри,Адриа,Адриан,Адриана,Адрианн,Адрианна, [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лен.
        /// </summary>
        public static string Flax {
            get {
                return ResourceManager.GetString("Flax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фураж.
        /// </summary>
        public static string Hay {
            get {
                return ResourceManager.GetString("Hay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на узи.
        /// </summary>
        public static string HorseStatsuEcho {
            get {
                return ResourceManager.GetString("HorseStatsuEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на аборт.
        /// </summary>
        public static string HorseStatusAbortion {
            get {
                return ResourceManager.GetString("HorseStatusAbortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на рост.
        /// </summary>
        public static string HorseStatusAge {
            get {
                return ResourceManager.GetString("HorseStatusAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на роды.
        /// </summary>
        public static string HorseStatusBirth {
            get {
                return ResourceManager.GetString("HorseStatusBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на морковь.
        /// </summary>
        public static string HorseStatusCarrot {
            get {
                return ResourceManager.GetString("HorseStatusCarrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на запись кск.
        /// </summary>
        public static string HorseStatusCenter {
            get {
                return ResourceManager.GetString("HorseStatusCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выписывание из кск.
        /// </summary>
        public static string HorseStatusCenterCancel {
            get {
                return ResourceManager.GetString("HorseStatusCenterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на соревнование.
        /// </summary>
        public static string HorseStatusCompetition {
            get {
                return ResourceManager.GetString("HorseStatusCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пить.
        /// </summary>
        public static string HorseStatusDrink {
            get {
                return ResourceManager.GetString("HorseStatusDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выбор экипировки.
        /// </summary>
        public static string HorseStatusEquipment {
            get {
                return ResourceManager.GetString("HorseStatusEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на корм.
        /// </summary>
        public static string HorseStatusFeed {
            get {
                return ResourceManager.GetString("HorseStatusFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на игры.
        /// </summary>
        public static string HorseStatusGame {
            get {
                return ResourceManager.GetString("HorseStatusGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на чистка.
        /// </summary>
        public static string HorseStatusGroom {
            get {
                return ResourceManager.GetString("HorseStatusGroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на случки.
        /// </summary>
        public static string HorseStatusMaleHorsing {
            get {
                return ResourceManager.GetString("HorseStatusMaleHorsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на смесь.
        /// </summary>
        public static string HorseStatusMash {
            get {
                return ResourceManager.GetString("HorseStatusMash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на миссия.
        /// </summary>
        public static string HorseStatusMission {
            get {
                return ResourceManager.GetString("HorseStatusMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на переименование.
        /// </summary>
        public static string HorseStatusRename {
            get {
                return ResourceManager.GetString("HorseStatusRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на запись резерв кск.
        /// </summary>
        public static string HorseStatusReserveCenter {
            get {
                return ResourceManager.GetString("HorseStatusReserveCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на возвращение на маму.
        /// </summary>
        public static string HorseStatusReturnToMom {
            get {
                return ResourceManager.GetString("HorseStatusReturnToMom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сон.
        /// </summary>
        public static string HorseStatusSleep {
            get {
                return ResourceManager.GetString("HorseStatusSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выбор специализации.
        /// </summary>
        public static string HorseStatusSpecialization {
            get {
                return ResourceManager.GetString("HorseStatusSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ласка.
        /// </summary>
        public static string HorseStatusStroke {
            get {
                return ResourceManager.GetString("HorseStatusStroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на тренировка.
        /// </summary>
        public static string HorseStatusTraining {
            get {
                return ResourceManager.GetString("HorseStatusTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на прогулка.
        /// </summary>
        public static string HorseStatusWalk {
            get {
                return ResourceManager.GetString("HorseStatusWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на хлыст.
        /// </summary>
        public static string HorseStatusWhip {
            get {
                return ResourceManager.GetString("HorseStatusWhip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 лет.
        /// </summary>
        public static string HorsingEdge10Years {
            get {
                return ResourceManager.GetString("HorsingEdge10Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 60 НЛНП.
        /// </summary>
        public static string HorsingEdge60NLNP {
            get {
                return ResourceManager.GetString("HorsingEdge60NLNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кожа.
        /// </summary>
        public static string Leather {
            get {
                return ResourceManager.GetString("Leather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во лошадей.
        /// </summary>
        public static string LimitHorses {
            get {
                return ResourceManager.GetString("LimitHorses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во ОР.
        /// </summary>
        public static string LimitOR {
            get {
                return ResourceManager.GetString("LimitOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти в соу.
        /// </summary>
        public static string LoginCoBtn {
            get {
                return ResourceManager.GetString("LoginCoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке соу аккаунтов!.
        /// </summary>
        public static string LoginCoErrorMessage1 {
            get {
                return ResourceManager.GetString("LoginCoErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка входу в соу!.
        /// </summary>
        public static string LoginCoErrorMessage2 {
            get {
                return ResourceManager.GetString("LoginCoErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string LoginCoPageCancelBtn {
            get {
                return ResourceManager.GetString("LoginCoPageCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string LoginCoPageLoginBtn {
            get {
                return ResourceManager.GetString("LoginCoPageLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось войти в соу!.
        /// </summary>
        public static string LoginErrorMessage1 {
            get {
                return ResourceManager.GetString("LoginErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка входа!.
        /// </summary>
        public static string LoginErrorMessage2 {
            get {
                return ResourceManager.GetString("LoginErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить.
        /// </summary>
        public static string LoginPageClearBtn {
            get {
                return ResourceManager.GetString("LoginPageClearBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string LoginPageDeleteBtn {
            get {
                return ResourceManager.GetString("LoginPageDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string LoginPageLoginBtn {
            get {
                return ResourceManager.GetString("LoginPageLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string LoginPageLoginText {
            get {
                return ResourceManager.GetString("LoginPageLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string LoginPagePasswordText {
            get {
                return ResourceManager.GetString("LoginPagePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string LoginPageProxyLoginText {
            get {
                return ResourceManager.GetString("LoginPageProxyLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string LoginPageProxyPasswordText {
            get {
                return ResourceManager.GetString("LoginPageProxyPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прокси.
        /// </summary>
        public static string LoginPageProxyText {
            get {
                return ResourceManager.GetString("LoginPageProxyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить данные.
        /// </summary>
        public static string LoginPageRememberChk {
            get {
                return ResourceManager.GetString("LoginPageRememberChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранненые аккаунты.
        /// </summary>
        public static string LoginPageSavedAccsText {
            get {
                return ResourceManager.GetString("LoginPageSavedAccsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер.
        /// </summary>
        public static string LoginPageServerText {
            get {
                return ResourceManager.GetString("LoginPageServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти из соу.
        /// </summary>
        public static string LogoutCoBtn {
            get {
                return ResourceManager.GetString("LogoutCoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменено!.
        /// </summary>
        public static string MainCancelMessage {
            get {
                return ResourceManager.GetString("MainCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лошадь метрва! Добавление не возможно!.
        /// </summary>
        public static string MainErrorMessage1 {
            get {
                return ResourceManager.GetString("MainErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Во время тренировок произошла ошибка! Все необходимые данные были записаны. Отправьте отчет об ошибке..
        /// </summary>
        public static string MainErrorMessage2 {
            get {
                return ResourceManager.GetString("MainErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное кол-во лошадей под данную схему (пара/полупара)!.
        /// </summary>
        public static string MainErrorMessage3 {
            get {
                return ResourceManager.GetString("MainErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт не соу!.
        /// </summary>
        public static string MainErrorMessage4 {
            get {
                return ResourceManager.GetString("MainErrorMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string MainPageAddBtn {
            get {
                return ResourceManager.GetString("MainPageAddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст.
        /// </summary>
        public static string MainPageAgeText {
            get {
                return ResourceManager.GetString("MainPageAgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во.
        /// </summary>
        public static string MainPageAmountText {
            get {
                return ResourceManager.GetString("MainPageAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОР.
        /// </summary>
        public static string MainPageAPText {
            get {
                return ResourceManager.GetString("MainPageAPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Морковь.
        /// </summary>
        public static string MainPageCarrotText {
            get {
                return ResourceManager.GetString("MainPageCarrotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string MainPageDeleteBtn {
            get {
                return ResourceManager.GetString("MainPageDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энергия.
        /// </summary>
        public static string MainPageEnergyText {
            get {
                return ResourceManager.GetString("MainPageEnergyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экю.
        /// </summary>
        public static string MainPageEquText {
            get {
                return ResourceManager.GetString("MainPageEquText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string MainPageExitBtn {
            get {
                return ResourceManager.GetString("MainPageExitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string MainPageFilterText {
            get {
                return ResourceManager.GetString("MainPageFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галоп.
        /// </summary>
        public static string MainPageGalopText {
            get {
                return ResourceManager.GetString("MainPageGalopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выездка.
        /// </summary>
        public static string MainPageGoText {
            get {
                return ResourceManager.GetString("MainPageGoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фураж.
        /// </summary>
        public static string MainPageHayText {
            get {
                return ResourceManager.GetString("MainPageHayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здоровье.
        /// </summary>
        public static string MainPageHealthText {
            get {
                return ResourceManager.GetString("MainPageHealthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string MainPageHorseNameText {
            get {
                return ResourceManager.GetString("MainPageHorseNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лошади.
        /// </summary>
        public static string MainPageHorseText {
            get {
                return ResourceManager.GetString("MainPageHorseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string MainPageInfoText {
            get {
                return ResourceManager.GetString("MainPageInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прыжки.
        /// </summary>
        public static string MainPageJumpText {
            get {
                return ResourceManager.GetString("MainPageJumpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string MainPageLoadBtn {
            get {
                return ResourceManager.GetString("MainPageLoadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти в соу.
        /// </summary>
        public static string MainPageLoginCoBtn {
            get {
                return ResourceManager.GetString("MainPageLoginCoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рысь.
        /// </summary>
        public static string MainPageLynxText {
            get {
                return ResourceManager.GetString("MainPageLynxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление аккаунтом.
        /// </summary>
        public static string MainPageManagerBtn {
            get {
                return ResourceManager.GetString("MainPageManagerBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смесь.
        /// </summary>
        public static string MainPageMeshText {
            get {
                return ResourceManager.GetString("MainPageMeshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Многострочный.
        /// </summary>
        public static string MainPageMultipleChk {
            get {
                return ResourceManager.GetString("MainPageMultipleChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string MainPageNameText {
            get {
                return ResourceManager.GetString("MainPageNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НЛНП.
        /// </summary>
        public static string MainPageNLNPText {
            get {
                return ResourceManager.GetString("MainPageNLNPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Овес.
        /// </summary>
        public static string MainPageOatText {
            get {
                return ResourceManager.GetString("MainPageOatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезагрузить заводы.
        /// </summary>
        public static string MainPageReloadFarmsBtn {
            get {
                return ResourceManager.GetString("MainPageReloadFarmsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить соу.
        /// </summary>
        public static string MainPageSaveCoBtn {
            get {
                return ResourceManager.GetString("MainPageSaveCoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема.
        /// </summary>
        public static string MainPageSchemeText {
            get {
                return ResourceManager.GetString("MainPageSchemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string MainPageSettingsBtn {
            get {
                return ResourceManager.GetString("MainPageSettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навыки.
        /// </summary>
        public static string MainPageSkillsText {
            get {
                return ResourceManager.GetString("MainPageSkillsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка.
        /// </summary>
        public static string MainPageSortText {
            get {
                return ResourceManager.GetString("MainPageSortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость.
        /// </summary>
        public static string MainPageSpeedText {
            get {
                return ResourceManager.GetString("MainPageSpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск.
        /// </summary>
        public static string MainPageStartBtn {
            get {
                return ResourceManager.GetString("MainPageStartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string MainPageStatusBtn {
            get {
                return ResourceManager.GetString("MainPageStatusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string MainPageStatusText {
            get {
                return ResourceManager.GetString("MainPageStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить.
        /// </summary>
        public static string MainPageStopBtn {
            get {
                return ResourceManager.GetString("MainPageStopBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        public static string MainPageTimeText {
            get {
                return ResourceManager.GetString("MainPageTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выносливость.
        /// </summary>
        public static string MainPageVitalityText {
            get {
                return ResourceManager.GetString("MainPageVitalityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт сохранен!.
        /// </summary>
        public static string MainSaveAccountMessage {
            get {
                return ResourceManager.GetString("MainSaveAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ааран,Аарен,Ааррон,Аб,Аббат,Абботт,Абей,Абелл,Абель,Абнар,Абнер,Абнор,Абот,Аботт,Абрам,Абран,Абрахам,Абсалон,Аверилл,Адам,Аддам,Аддисон,Аден,Адисон,Адиссон,Адлэй,Адней,Адольф,Адриан,Адэйр,Адэр,Азия,Азэлстан,Айбл,Айзек,Айк,Ак,Акей,Акерлеа,Акерлей,Акерли,Аки,Аклеа,Аклей,Акли,Актон,Акэль,Алан,Аластеир,Аластэйр,Алвар,Алвен,Алви,Алвин,Алвис,Алгар,Алджернон,Алеистер,Алек,Алекс,Александр,Ален,Алестер,Алжир,Алик,Аликс,Алисандр,Алисдэйр,Алиссандр,Алистер,Алистэйр,Аллан,Аллен,Аллин,Аллистер,Аллистир,Аллистэйр,Алтон,А [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при покупке!.
        /// </summary>
        public static string ManagerBuyErrorMessage {
            get {
                return ResourceManager.GetString("ManagerBuyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Яблоки.
        /// </summary>
        public static string ManagerPageApplesText {
            get {
                return ResourceManager.GetString("ManagerPageApplesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купить.
        /// </summary>
        public static string ManagerPageBuyBtn {
            get {
                return ResourceManager.GetString("ManagerPageBuyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Морковь.
        /// </summary>
        public static string ManagerPageCarrotText {
            get {
                return ResourceManager.GetString("ManagerPageCarrotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лен.
        /// </summary>
        public static string ManagerPageFlaxText {
            get {
                return ResourceManager.GetString("ManagerPageFlaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фураж.
        /// </summary>
        public static string ManagerPageHayText {
            get {
                return ResourceManager.GetString("ManagerPageHayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кожа.
        /// </summary>
        public static string ManagerPageLeatherText {
            get {
                return ResourceManager.GetString("ManagerPageLeatherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Овес.
        /// </summary>
        public static string ManagerPageOatText {
            get {
                return ResourceManager.GetString("ManagerPageOatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string ManagerPageReturnBtn {
            get {
                return ResourceManager.GetString("ManagerPageReturnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Песок.
        /// </summary>
        public static string ManagerPageSandText {
            get {
                return ResourceManager.GetString("ManagerPageSandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продать.
        /// </summary>
        public static string ManagerPageSellBtn {
            get {
                return ResourceManager.GetString("ManagerPageSellBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навоз.
        /// </summary>
        public static string ManagerPageShitText {
            get {
                return ResourceManager.GetString("ManagerPageShitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Железо.
        /// </summary>
        public static string ManagerPageSteelText {
            get {
                return ResourceManager.GetString("ManagerPageSteelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Солома.
        /// </summary>
        public static string ManagerPageStrawText {
            get {
                return ResourceManager.GetString("ManagerPageStrawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пшеница.
        /// </summary>
        public static string ManagerPageWheatText {
            get {
                return ResourceManager.GetString("ManagerPageWheatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дерево.
        /// </summary>
        public static string ManagerPageWoodText {
            get {
                return ResourceManager.GetString("ManagerPageWoodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при продаже!.
        /// </summary>
        public static string ManagerSellErrorMessage {
            get {
                return ResourceManager.GetString("ManagerSellErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смесь.
        /// </summary>
        public static string Mash {
            get {
                return ResourceManager.GetString("Mash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не введено имя!.
        /// </summary>
        public static string NamesWindowErrorMessage1 {
            get {
                return ResourceManager.GetString("NamesWindowErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не продавать.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Овес.
        /// </summary>
        public static string Oat {
            get {
                return ResourceManager.GetString("Oat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОР.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выездка.
        /// </summary>
        public static string PGDressage {
            get {
                return ResourceManager.GetString("PGDressage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галоп.
        /// </summary>
        public static string PGGalop {
            get {
                return ResourceManager.GetString("PGGalop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прыжки.
        /// </summary>
        public static string PGJump {
            get {
                return ResourceManager.GetString("PGJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рысь.
        /// </summary>
        public static string PGLynx {
            get {
                return ResourceManager.GetString("PGLynx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ничего.
        /// </summary>
        public static string PGNone {
            get {
                return ResourceManager.GetString("PGNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость.
        /// </summary>
        public static string PGSpeed {
            get {
                return ResourceManager.GetString("PGSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выносливость.
        /// </summary>
        public static string PGVitality {
            get {
                return ResourceManager.GetString("PGVitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка отправки отчета.
        /// </summary>
        public static string ReportErrorMessage {
            get {
                return ResourceManager.GetString("ReportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты (страница вк/почта).
        /// </summary>
        public static string ReportPageContactsText {
            get {
                return ResourceManager.GetString("ReportPageContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        public static string ReportPageMessageText {
            get {
                return ResourceManager.GetString("ReportPageMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string ReportPageReturnBtn {
            get {
                return ResourceManager.GetString("ReportPageReturnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string ReportPageSendBtn {
            get {
                return ResourceManager.GetString("ReportPageSendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение отправлено!.
        /// </summary>
        public static string ReportSuccessMessage {
            get {
                return ResourceManager.GetString("ReportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Песок.
        /// </summary>
        public static string Sand {
            get {
                return ResourceManager.GetString("Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полупара.
        /// </summary>
        public static string SchemeTypeHalfPair {
            get {
                return ResourceManager.GetString("SchemeTypeHalfPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пара.
        /// </summary>
        public static string SchemeTypePair {
            get {
                return ResourceManager.GetString("SchemeTypePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Арабский.
        /// </summary>
        public static string ServerArabic {
            get {
                return ResourceManager.GetString("ServerArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Австралия.
        /// </summary>
        public static string ServerAustralia {
            get {
                return ResourceManager.GetString("ServerAustralia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Болгария.
        /// </summary>
        public static string ServerBulgaria {
            get {
                return ResourceManager.GetString("ServerBulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канада.
        /// </summary>
        public static string ServerCanada {
            get {
                return ResourceManager.GetString("ServerCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Англия.
        /// </summary>
        public static string ServerEngland {
            get {
                return ResourceManager.GetString("ServerEngland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Франция Gaia.
        /// </summary>
        public static string ServerFranceGaia {
            get {
                return ResourceManager.GetString("ServerFranceGaia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фрация Ouranos.
        /// </summary>
        public static string ServerFranceOuranos {
            get {
                return ResourceManager.GetString("ServerFranceOuranos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Немецкий.
        /// </summary>
        public static string ServerGermany {
            get {
                return ResourceManager.GetString("ServerGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интернациональный.
        /// </summary>
        public static string ServerInternational {
            get {
                return ResourceManager.GetString("ServerInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Норвегия.
        /// </summary>
        public static string ServerNorway {
            get {
                return ResourceManager.GetString("ServerNorway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Польша.
        /// </summary>
        public static string ServerPoland {
            get {
                return ResourceManager.GetString("ServerPoland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Румыния.
        /// </summary>
        public static string ServerRomain {
            get {
                return ResourceManager.GetString("ServerRomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Россия.
        /// </summary>
        public static string ServerRussia {
            get {
                return ResourceManager.GetString("ServerRussia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испания.
        /// </summary>
        public static string ServerSpain {
            get {
                return ResourceManager.GetString("ServerSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Швеция.
        /// </summary>
        public static string ServerSweden {
            get {
                return ResourceManager.GetString("ServerSweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на США.
        /// </summary>
        public static string ServerUSA {
            get {
                return ResourceManager.GetString("ServerUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при загрузке настроек из файла! Убедитесь, что файл был создан текущей версией программы! Ошибка.
        /// </summary>
        public static string SettingsErrorMessage1 {
            get {
                return ResourceManager.GetString("SettingsErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при сохранении настроек в файла! Ошибка.
        /// </summary>
        public static string SettingsErrorMessage2 {
            get {
                return ResourceManager.GetString("SettingsErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Был выставлен резервный КСК, но не выбран свой или не введен ID! Выставьте правильно настройки и повторите!.
        /// </summary>
        public static string SettingsErrorMessage3 {
            get {
                return ResourceManager.GetString("SettingsErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С абортами.
        /// </summary>
        public static string SettingsPageAbortionChk {
            get {
                return ResourceManager.GetString("SettingsPageAbortionChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string SettingsPageAcceptBtn {
            get {
                return ResourceManager.GetString("SettingsPageAcceptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аффикс.
        /// </summary>
        public static string SettingsPageAffixText {
            get {
                return ResourceManager.GetString("SettingsPageAffixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амуниция.
        /// </summary>
        public static string SettingsPageAmunityionText {
            get {
                return ResourceManager.GetString("SettingsPageAmunityionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бинты.
        /// </summary>
        public static string SettingsPageBandageChk {
            get {
                return ResourceManager.GetString("SettingsPageBandageChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупка моркови/смеси.
        /// </summary>
        public static string SettingsPageBuyCarrotMeshChk {
            get {
                return ResourceManager.GetString("SettingsPageBuyCarrotMeshChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупка еды.
        /// </summary>
        public static string SettingsPageBuyFoodChk {
            get {
                return ResourceManager.GetString("SettingsPageBuyFoodChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string SettingsPageCancelBtn {
            get {
                return ResourceManager.GetString("SettingsPageCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КСК.
        /// </summary>
        public static string SettingsPageCenterText {
            get {
                return ResourceManager.GetString("SettingsPageCenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string SettingsPageChangeBtn {
            get {
                return ResourceManager.GetString("SettingsPageChangeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выписывать из КСК.
        /// </summary>
        public static string SettingsPageDeleteFromCenterChk {
            get {
                return ResourceManager.GetString("SettingsPageDeleteFromCenterChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завод.
        /// </summary>
        public static string SettingsPageFarmText {
            get {
                return ResourceManager.GetString("SettingsPageFarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя жен.
        /// </summary>
        public static string SettingsPageFemalNameText {
            get {
                return ResourceManager.GetString("SettingsPageFemalNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налобник.
        /// </summary>
        public static string SettingsPageForeheadChk {
            get {
                return ResourceManager.GetString("SettingsPageForeheadChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игры.
        /// </summary>
        public static string SettingsPageGamesChk {
            get {
                return ResourceManager.GetString("SettingsPageGamesChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие.
        /// </summary>
        public static string SettingsPageGeneralText {
            get {
                return ResourceManager.GetString("SettingsPageGeneralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здоровье.
        /// </summary>
        public static string SettingsPageHealthText {
            get {
                return ResourceManager.GetString("SettingsPageHealthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тяжеловозы.
        /// </summary>
        public static string SettingsPageHighWeightChk {
            get {
                return ResourceManager.GetString("SettingsPageHighWeightChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число случек от ♂ в парт.
        /// </summary>
        public static string SettingsPageHorsingAmountText {
            get {
                return ResourceManager.GetString("SettingsPageHorsingAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случки/Роды.
        /// </summary>
        public static string SettingsPageHorsingBirthText {
            get {
                return ResourceManager.GetString("SettingsPageHorsingBirthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случки с.
        /// </summary>
        public static string SettingsPageHorsingWithText {
            get {
                return ResourceManager.GetString("SettingsPageHorsingWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длительность.
        /// </summary>
        public static string SettingsPageLengthText {
            get {
                return ResourceManager.GetString("SettingsPageLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Урок с 2-х лет.
        /// </summary>
        public static string SettingsPageLesson2YearChk {
            get {
                return ResourceManager.GetString("SettingsPageLesson2YearChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Урок после трен..
        /// </summary>
        public static string SettingsPageLessonAfterChk {
            get {
                return ResourceManager.GetString("SettingsPageLessonAfterChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничения.
        /// </summary>
        public static string SettingsPageLimitsText {
            get {
                return ResourceManager.GetString("SettingsPageLimitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string SettingsPageLoadBtn {
            get {
                return ResourceManager.GetString("SettingsPageLoadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя муж.
        /// </summary>
        public static string SettingsPageMaleNameText {
            get {
                return ResourceManager.GetString("SettingsPageMaleNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параллельная пара.
        /// </summary>
        public static string SettingsPageParallelPairChk {
            get {
                return ResourceManager.GetString("SettingsPageParallelPairChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Паузы.
        /// </summary>
        public static string SettingsPagePausesChk {
            get {
                return ResourceManager.GetString("SettingsPagePausesChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приписка к ГП.
        /// </summary>
        public static string SettingsPagePGPreffixText {
            get {
                return ResourceManager.GetString("SettingsPagePGPreffixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ставить ГП.
        /// </summary>
        public static string SettingsPagePlacePGChk {
            get {
                return ResourceManager.GetString("SettingsPagePlacePGChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случайные имена.
        /// </summary>
        public static string SettingsPageRandomNamesChk {
            get {
                return ResourceManager.GetString("SettingsPageRandomNamesChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резервный.
        /// </summary>
        public static string SettingsPageReserveChk {
            get {
                return ResourceManager.GetString("SettingsPageReserveChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить.
        /// </summary>
        public static string SettingsPageResetBtn {
            get {
                return ResourceManager.GetString("SettingsPageResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SettingsPageSaveBtn {
            get {
                return ResourceManager.GetString("SettingsPageSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема.
        /// </summary>
        public static string SettingsPageSchemeText {
            get {
                return ResourceManager.GetString("SettingsPageSchemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свой.
        /// </summary>
        public static string SettingsPageSelfChk {
            get {
                return ResourceManager.GetString("SettingsPageSelfChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специализация.
        /// </summary>
        public static string SettingsPageSpecializationText {
            get {
                return ResourceManager.GetString("SettingsPageSpecializationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если не уверены содержит ваш аффикс англ. буквы под видом русских, копируйте его с игры!.
        /// </summary>
        public static string SettingsPageTooltip {
            get {
                return ResourceManager.GetString("SettingsPageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренировка/Соревнования.
        /// </summary>
        public static string SettingsPageTrainingText {
            get {
                return ResourceManager.GetString("SettingsPageTrainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип тренировки.
        /// </summary>
        public static string SettingsPageTrainingTypeText {
            get {
                return ResourceManager.GetString("SettingsPageTrainingTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хлыст.
        /// </summary>
        public static string SettingsPageWhipChk {
            get {
                return ResourceManager.GetString("SettingsPageWhipChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коб.
        /// </summary>
        public static string SexFemale {
            get {
                return ResourceManager.GetString("SexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жер.
        /// </summary>
        public static string SexMale {
            get {
                return ResourceManager.GetString("SexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навоз.
        /// </summary>
        public static string Shit {
            get {
                return ResourceManager.GetString("Shit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст.
        /// </summary>
        public static string SortAge {
            get {
                return ResourceManager.GetString("SortAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения.
        /// </summary>
        public static string SortDate {
            get {
                return ResourceManager.GetString("SortDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string SortName {
            get {
                return ResourceManager.GetString("SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Генетический потенциал.
        /// </summary>
        public static string SortPG {
            get {
                return ResourceManager.GetString("SortPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порода.
        /// </summary>
        public static string SortRace {
            get {
                return ResourceManager.GetString("SortRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навыки.
        /// </summary>
        public static string SortSkills {
            get {
                return ResourceManager.GetString("SortSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классика.
        /// </summary>
        public static string SpecializationClassic {
            get {
                return ResourceManager.GetString("SpecializationClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вестерн.
        /// </summary>
        public static string SpecializationWestern {
            get {
                return ResourceManager.GetString("SpecializationWestern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во.
        /// </summary>
        public static string StatusPageAmount {
            get {
                return ResourceManager.GetString("StatusPageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во лошадей.
        /// </summary>
        public static string StatusPageAmountHorsesText {
            get {
                return ResourceManager.GetString("StatusPageAmountHorsesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амуниция.
        /// </summary>
        public static string StatusPageAmunitionText {
            get {
                return ResourceManager.GetString("StatusPageAmunitionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бинты.
        /// </summary>
        public static string StatusPageBandagesText {
            get {
                return ResourceManager.GetString("StatusPageBandagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уздечки.
        /// </summary>
        public static string StatusPageBridleText {
            get {
                return ResourceManager.GetString("StatusPageBridleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налобники.
        /// </summary>
        public static string StatusPageForeheadText {
            get {
                return ResourceManager.GetString("StatusPageForeheadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение здоровья.
        /// </summary>
        public static string StatusPageLimitHealthText {
            get {
                return ResourceManager.GetString("StatusPageLimitHealthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение.
        /// </summary>
        public static string StatusPageLimitText {
            get {
                return ResourceManager.GetString("StatusPageLimitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вальтрапы.
        /// </summary>
        public static string StatusPageRampText {
            get {
                return ResourceManager.GetString("StatusPageRampText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string StatusPageReturnBtn {
            get {
                return ResourceManager.GetString("StatusPageReturnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Седла.
        /// </summary>
        public static string StatusPageSadleText {
            get {
                return ResourceManager.GetString("StatusPageSadleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема.
        /// </summary>
        public static string StatusPageSchemeText {
            get {
                return ResourceManager.GetString("StatusPageSchemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специализация.
        /// </summary>
        public static string StatusPageSpecializationText {
            get {
                return ResourceManager.GetString("StatusPageSpecializationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Железо.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Солома.
        /// </summary>
        public static string Straw {
            get {
                return ResourceManager.GetString("Straw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Несколько часов.
        /// </summary>
        public static string TimeFewHours {
            get {
                return ResourceManager.GetString("TimeFewHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на месяц.
        /// </summary>
        public static string TimeMonth1 {
            get {
                return ResourceManager.GetString("TimeMonth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на месяца.
        /// </summary>
        public static string TimeMonth2 {
            get {
                return ResourceManager.GetString("TimeMonth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на месяцев.
        /// </summary>
        public static string TimeMonth3 {
            get {
                return ResourceManager.GetString("TimeMonth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на год.
        /// </summary>
        public static string TimeYear1 {
            get {
                return ResourceManager.GetString("TimeYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на года.
        /// </summary>
        public static string TimeYear2 {
            get {
                return ResourceManager.GetString("TimeYear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на лет.
        /// </summary>
        public static string TimeYear3 {
            get {
                return ResourceManager.GetString("TimeYear3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конкур.
        /// </summary>
        public static string TrainingClassicConcur {
            get {
                return ResourceManager.GetString("TrainingClassicConcur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кросс.
        /// </summary>
        public static string TrainingClassicCross {
            get {
                return ResourceManager.GetString("TrainingClassicCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выездка(с).
        /// </summary>
        public static string TrainingClassicDressage {
            get {
                return ResourceManager.GetString("TrainingClassicDressage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галоп(с).
        /// </summary>
        public static string TrainingClassicGalop {
            get {
                return ResourceManager.GetString("TrainingClassicGalop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рысь(с).
        /// </summary>
        public static string TrainingClassicLynx {
            get {
                return ResourceManager.GetString("TrainingClassicLynx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выездка.
        /// </summary>
        public static string TrainingDressage {
            get {
                return ResourceManager.GetString("TrainingDressage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лес.
        /// </summary>
        public static string TrainingForest {
            get {
                return ResourceManager.GetString("TrainingForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галоп.
        /// </summary>
        public static string TrainingGalop {
            get {
                return ResourceManager.GetString("TrainingGalop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прыжки.
        /// </summary>
        public static string TrainingJump {
            get {
                return ResourceManager.GetString("TrainingJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рысь.
        /// </summary>
        public static string TrainingLynx {
            get {
                return ResourceManager.GetString("TrainingLynx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Горы.
        /// </summary>
        public static string TrainingMountain {
            get {
                return ResourceManager.GetString("TrainingMountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость.
        /// </summary>
        public static string TrainingSpeed {
            get {
                return ResourceManager.GetString("TrainingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выносливость.
        /// </summary>
        public static string TrainingVitality {
            get {
                return ResourceManager.GetString("TrainingVitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бочки.
        /// </summary>
        public static string TrainingWesternBarell {
            get {
                return ResourceManager.GetString("TrainingWesternBarell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каттинг.
        /// </summary>
        public static string TrainingWesternCutting {
            get {
                return ResourceManager.GetString("TrainingWesternCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плеже.
        /// </summary>
        public static string TrainingWesternPlege {
            get {
                return ResourceManager.GetString("TrainingWesternPlege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейнинг.
        /// </summary>
        public static string TrainingWesternRaining {
            get {
                return ResourceManager.GetString("TrainingWesternRaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трейл.
        /// </summary>
        public static string TrainingWesternTrail {
            get {
                return ResourceManager.GetString("TrainingWesternTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В команде .
        /// </summary>
        public static string TrainTypeTeam {
            get {
                return ResourceManager.GetString("TrainTypeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без команды.
        /// </summary>
        public static string TrainTypeWithoutTeam {
            get {
                return ResourceManager.GetString("TrainTypeWithoutTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пшеница.
        /// </summary>
        public static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла какая-то ошибка! Обратитесь к администрации!.
        /// </summary>
        public static string WindowErrorMessage1 {
            get {
                return ResourceManager.GetString("WindowErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружена попытка несанкционированого доступа!.
        /// </summary>
        public static string WindowErrorMessage2 {
            get {
                return ResourceManager.GetString("WindowErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша подписка не активна или не соотвествует уровень!.
        /// </summary>
        public static string WindowErrorMessage3 {
            get {
                return ResourceManager.GetString("WindowErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно обновление.
        /// </summary>
        public static string WindowUpdateMessage1 {
            get {
                return ResourceManager.GetString("WindowUpdateMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустите лаунчер чтобы обновиться..
        /// </summary>
        public static string WindowUpdateMessage2 {
            get {
                return ResourceManager.GetString("WindowUpdateMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дерево.
        /// </summary>
        public static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
    }
}
